[general]
#apiEndpoint =
#apiEndpointText =
#defaultSessionEnvironment =
siteDescription = "Debug"
connectionMode = "SESSION"
allowChangeSigninMode = true
signupSupport = false
allowSignout = true
allowAnonymousChangePassword = false
allowProjectResourceMonitor = true
allowManualImageNameForSession = false
#loginAttemptLimit = 5
#loginBlockTime = 180
debug = true

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"
#proxyBaseURL = ""
disableCertCheck = true

[resources]
openPortToPublic = true
maxCPUCoresPerContainer = 256
maxCUDADevicesPerContainer = 16
maxCUDASharesPerContainer = 16
maxShmPerContainer = 1
maxFileUploadSize = 4294967296 # 4GB. 4294967296

[environments]
#allowlist = ""

[server]
webServerURL =

[plugin]
#login = "signup-cloud.js"
#sidebar = "report-cloud.js"
