[general]
#apiEndpoint =
#apiEndpointText =
#defaultSessionEnvironment =
siteDescription = "Console"
connectionMode = "SESSION"
allowChangeSigninMode = true
signupSupport = false
allowSignout = true
allowAnonymousChangePassword = false
allowProjectResourceMonitor = true
debug = true

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"
#proxyBaseURL = ""
disableCertCheck = true

[server]
consoleServerURL =

[plugin]
#login = "signup-cloud.js"
#sidebar = "report-cloud.js"
