[general]
#apiEndpoint = ""
#apiEndpointText = ""
#defaultSessionEnvironment = ""
#defaultImportEnvironment = ""
siteDescription = "Debug"
connectionMode = "SESSION"
allowChangeSigninMode = true
signupSupport = false
allowSignout = true
allowAnonymousChangePassword = false
allowProjectResourceMonitor = true
allowManualImageNameForSession = false
#allowSignupWithoutConfirmation = true
#autoLogout = false
#loginAttemptLimit = 5
#loginBlockTime = 180
debug = true
#maskUserInfo = false

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"
#proxyBaseURL = ""
#proxyListenIP = ""
#autoPortSelection = true
disableCertCheck = true

[menu]
#blocklist = ""

[resources]
openPortToPublic = true
maxCPUCoresPerContainer = 256
maxMemoryPerContainer = 512
maxCUDADevicesPerContainer = 16
maxCUDASharesPerContainer = 16
maxShmPerContainer = 1
maxFileUploadSize = 4294967296 # 4GB. 4294967296

[environments]
#allowlist = ""

[server]
webServerURL =

[plugin]
# Reserved to load plugins
#login = "signup-cloud.js"
#sidebar = "report-cloud.js"
#page = "test-plugin1,test-plugin2" # Separated by comma.

#[license]
#This field is generated by console-server.
