[general]
#apiEndpoint =
#apiEndpointText =
#defaultSessionEnvironment =
siteDescription = "Console"
connectionMode = "SESSION"
allowChangeSigninMode = true
signupSupport = false
allowSignout = true
allowAnonymousChangePassword = false
allowProjectResourceMonitor = true
#loginAttemptLimit = 5
#loginBlockTime = 180
debug = true

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"
#proxyBaseURL = ""
disableCertCheck = true

[resources]
openPortToPublic = true
maxCPUCoresPerSession = 256
maxCUDADevicesPerSession = 16
maxCUDASharesPerSession = 16
maxShmPerSession = 1
maxFileUploadSize = 4294967296 # 4GB. 4294967296

[server]
consoleServerURL =

[plugin]
#login = "signup-cloud.js"
#sidebar = "report-cloud.js"
