[general]
#apiEndpoint = ""
#apiEndpointText = ""
#defaultSessionEnvironment = ""
#defaultImportEnvironment = ""
siteDescription = "Desktop"
connectionMode = "SESSION"
allowChangeSigninMode = true
signupSupport = false
allowSignout = false
allowAnonymousChangePassword = false
allowProjectResourceMonitor = true
allowManualImageNameForSession = false
#allowSignupWithoutConfirmation = true
#autoLogout = false
#loginAttemptLimit = 5
#loginBlockTime = 180
debug = false
#maskUserInfo = false

[wsproxy]
proxyURL = "https://wsproxy.onprem.backend.ai:9443/"
#proxyBaseURL = ""
#proxyListenIP = ""
#autoPortSelection = true
disableCertCheck = false

[menu]
#blocklist = ""

[resources]
openPortToPublic = true
maxCPUCoresPerContainer = 4096
maxMemoryPerContainer = 16384
maxCUDADevicesPerContainer = 2048
maxCUDASharesPerContainer = 4096
maxShmPerContainer = 512
maxFileUploadSize = 68719476736 # 64GB.

[environments]
#allowlist = ""

[server]
webServerURL =

[plugin]
# Reserved to load plugins
#login = "signup-cloud.js"
#sidebar = "report-cloud.js"
#page = "test-plugin1,test-plugin2" # Separated by comma.

#[license]
#This field is generated by console-server.